import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import GameContextProvider from "@/context/game-context";

const font = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Super Tic-Tac-Toe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} h-screen w-screen flex flex-col`}>
        <GameContextProvider>{children}</GameContextProvider>
      </body>
    </html>
  );
}
